name: "Make CI Release"

on:
  workflow_dispatch:
    inputs:
      ci-run-id:
        description: "Run ID of CI workflow"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts for last successful CI workflow
      if: ${{ !github.event.inputs.ci-run-id }}
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci-build.yml
        workflow_conclusion: success

    - name: Download artifacts for CI workflow with provided run id
      if: ${{ github.event.inputs.ci-run-id }}
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci-build.yml
        run_id: ${{ github.event.inputs.ci-run-id }}

    - name: Initialize version
      run: echo "KLOGG_VERSION=`cat klogg_version/klogg_version.txt`" >> $GITHUB_ENV

    - name: Display structure of downloaded files
      run: ls -R ./packages-*

    - name: Setup Sentry CLI
      uses: mathrix-education/setup-sentry-cli@0.1.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        token: ${{ secrets.SENTRY_TOKEN }}
        organization: anton-filimonov
        project: klogg

    - name: Create Sentry release
      shell: sh
      run: |
        sentry-cli releases new $KLOGG_VERSION
        sentry-cli releases set-commits --auto $KLOGG_VERSION

    - name: Upload symbols linux
      shell: sh
      run: |
        sentry-cli upload-dif ./packages-bionic/klogg_bionic.debug  ./packages-bionic/klogg_bionic
        sentry-cli upload-dif ./packages-focal/klogg_focal.debug ./packages-focal/klogg_focal
        sentry-cli upload-dif ./packages-jammy/klogg_jammy.debug ./packages-jammy/klogg_jammy
        sentry-cli upload-dif ./packages-oracle/klogg_oracle.debug ./packages-oracle/klogg_oracle
        sentry-cli upload-dif ./packages-appimage/klogg_appimage.debug  ./packages-appimage/klogg_appimage
        rm -rf ./packages-bionic/klogg_bionic 
        rm -rf ./packages-focal/klogg_focal
        rm -rf ./packages-jammy/klogg_jammy
        rm -rf ./packages-oracle/klogg_oracle
        rm -rf ./packages-oracle/klogg_oracle7
        rm -rf ./packages-appimage/klogg_appimage

    - name: Upload symbols mac
      shell: sh
      run: |
        sentry-cli upload-dif ./packages-macos-qt5/klogg-Qt5.app/Contents/MacOS/klogg ./packages-macos-qt5/klogg-Qt5.dSym
        sentry-cli upload-dif ./packages-macos-qt6/klogg-Qt6.app/Contents/MacOS/klogg ./packages-macos-qt6/klogg-Qt6.dSym
        rm -rf ./packages-macos-qt5/klogg-Qt5.app
        rm -rf ./packages-macos-qt6/klogg-Qt6.app

    - name: Upload symbols win
      shell: sh
      run: |
        sentry-cli upload-dif ./packages-windows-x64-qt5/klogg-$KLOGG_VERSION-x64-Qt5-pdb.zip
        sentry-cli upload-dif ./packages-windows-x86-qt5/klogg-$KLOGG_VERSION-x86-Qt5-pdb.zip 
        sentry-cli upload-dif ./packages-windows-x64-qt6/klogg-$KLOGG_VERSION-x64-Qt6-pdb.zip

    - name: Release win
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.KLOGG_GITHUB_TOKEN }}
        automatic_release_tag: continuous-win
        prerelease: true
        files: |
          ./packages-windows-x64-qt5/*
          ./packages-windows-x86-qt5/*
          ./packages-windows-x64-qt6/*

    - name: Release linux
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.KLOGG_GITHUB_TOKEN }}
        automatic_release_tag: continuous-linux
        prerelease: true
        files: |
          ./packages-bionic/*
          ./packages-focal/*
          ./packages-jammy/*
          ./packages-oracle/*
          ./packages-oracle7/*
          ./packages-appimage/*

    - name: Release mac
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.KLOGG_GITHUB_TOKEN }}
        automatic_release_tag: continuous-osx
        prerelease: true
        files: |
          ./packages-macos-qt5/*
          ./packages-macos-qt6/*

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_NEW_VERSIONS_WEBHOOK }}
        DISCORD_EMBEDS: '[{"title": "Windows", "url": "https://github.com/variar/klogg/releases/tag/continuous-win"}, {"title": "Linux", "url": "https://github.com/variar/klogg/releases/tag/continuous-linux"}, {"title": "Mac", "url": "https://github.com/variar/klogg/releases/tag/continuous-osx"}]'
      uses: Ilshidur/action-discord@master
      with:
        args: 'New CI build {{KLOGG_VERSION}} has been released!'




   
